services:

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - app
    networks:
      - webapp

  app:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/laravel
    networks:
      - webapp

networks:
  webapp:
